### ISSUE TITLE
Fix chat database and display

### ISSUE THREAD

**Issue by TMGBNoodle** [hspayde/Gamers_Grotto#18]
Chats are successfully sent to the database, but retrieving them is buggy, and when chats are sent they duplicate for some reason. 

Chats also do not display above players head

**Comment by cfp04** [comment]
I would to try to fix this

I pulled the code to look at it, and I am getting some "permission-denied" Firebase errors.
Maybe the dev permissions on your firestore database expired? If that is the case, I will need that fixed before I can work on the code.
