### ISSUE TITLE
Make *New Player Object* Widget

### ISSUE THREAD

**Issue by hspayde** [hspayde/Gamers_Grotto#4]
We need to create the widget that displays on the home screen and makes the player object.

**Comment by TMGBNoodle** [comment]
this is what my little dots look like, we have to recreate the widget every time an object moves so make sure the widget can take an x position, a y position, and a color.
`Positioned(
 left:calculateMoveX(player),
 top:calculateMoveY(player),
 child: CircleAvatar(backgroundColor: player.color,)
 )`

**Comment by hspayde** [comment]
Finished this.
